config/routes.rb
Rails.application.routes.draw do

  resources :soliciteds, except: [:new, :destroy, :index]

  resources :beneficiarios

  resources :solicituds, except: [:edit]
  post '/solicituds/confirmar/:id',    to: 'solicituds#confirmar',      as: 'confirmar_solicitud'
  post '/solicituds/reservar/:id',     to: 'solicituds#reservar',       as: 'reservar_solicitud'
  post '/solicituds/liberar/:id',      to: 'solicituds#liberar',        as: 'liberar_solicitud'
  post '/solicituds/entregar/:id',     to: 'solicituds#entregar',       as: 'entregar_solicitud'
  post '/solicituds/rechazar/:id',     to: 'solicituds#rechazar',       as: 'rechazar_solicitud'
  post '/solicituds/activar/:id',      to: 'solicituds#activar',        as: 'activar_solicitud'
  get '/solicitud/solicitud/:id',      to: 'solicituds#descargar_sol',  as: 'nueva_sol'

  get 'welcome/thankyou'

  get '/reportes/transparencia',     to: 'reportes#transparencia',        as: 'reportes_transparencia'
  get '/reporte/transparencia/:id',  to: 'reportes#transparencia_show',   as: 'reporte_perfil_transparencia'

  resources :implementos

  resources :expedientes

  resources :idiomas

  resources :pueblos

  resources :municipios

  resources :departamentos

  get 'user_dashboard/show'
  get 'user_dashboard/departamentos', as: 'dash_deps'

  resources :pages

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :articles, except: [:new, :destroy]

  devise_for  :users,   controllers: { registrations: 'registrations' }
  resources   :users,   only: [:index, :edit_user]

  get     '/user/:id',              to: 'user#show',          as: :user
  get     '/users/new_user',        to: 'users#new_user',     as: 'admins_new_user'
  post    '/users/create_user',     to: 'users#create_user',  as: 'admins_create_user'
  get     '/users/edit_user/:id',   to: 'users#edit_user',    as: 'admins_edit_user'
  patch   '/users/update_user/:id', to: 'users#update_user',  as: 'admins_update_user'
  delete  '/user/:id',              to: 'users#destroy_user', as: 'admins_destroy_user'

  root 'welcome#index'

end

app/models/beneficiario.rb
# == Schema Information
#
# Table name: beneficiarios
#
#  id                       :integer          not null, primary key
#  cui                      :string(255)
#  first_name               :string(255)
#  second_first_name        :string(255)
#  first_last_name          :string(255)
#  second_last_name         :string(255)
#  created_at               :datetime
#  updated_at               :datetime
#  solicitud_id             :integer
#  departamento             :string(255)
#  municipio                :string(255)
#  pueblo                   :string(255)
#  idioma                   :string(255)
#  birth_date               :date
#  no_partida_nacimiento    :string(255)
#  folio_partida_nacimiento :string(255)
#  libro_partida_nacimiento :string(255)
#  entidad                  :string(255)
#

class Beneficiario < ActiveRecord::Base
  validates :cui, :first_name, :first_last_name, :departamento, :municipio, presence: true
  belongs_to :solicitud

  public
    def age(bd)
      today = Date.today()
      birthday = bd

      a = today.year - birthday.year
      a = a - 1 if (
      birthday.month >  today.month or
          (birthday.month >= today.month and birthday.day > today.day)
      )
      return a
    end

  #before_save bool_turn(:menor)

  #def bool_turn(menor)
  #  if menor == 'Menor de Edad'
  #    menor = 0
  #  else
  #    menor = 1
  #  end
  #end
end

app/controllers/beneficiarios_controller.rb
class BeneficiariosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_beneficiario, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html, :json

  def index
    @beneficiarios = Beneficiario.all.paginate(:page => params[:page], :per_page => 20)
    respond_with(@beneficiarios)
  end

  def show
    respond_with(@beneficiario)
  end

  def new
    @beneficiario = Beneficiario.new
    respond_with(@beneficiario)
  end

  def edit
  end

  def create
    @beneficiario = Beneficiario.new(beneficiario_params)
    @beneficiario.save
    respond_with(@beneficiario)
  end

  def update
    @beneficiario.update(beneficiario_params)
    respond_with(@beneficiario)
  end

  def destroy
    @beneficiario.destroy
    respond_with(@beneficiario)
  end

  private
    def set_beneficiario
      @beneficiario = Beneficiario.find(params[:id])
    end

    def beneficiario_params
      params.require(:beneficiario).permit(:cui, :first_name, :second_first_name, :first_last_name, :second_last_name, :menor)
    end
end

app/helpers/beneficiarios_helper.rb
module BeneficiariosHelper
end

app/views/beneficiarios/_form.html.haml
= simple_form_for(@beneficiario) do |f|
  = f.error_notification

  .form-inputs
    = f.input :cui
    = f.input :first_name
    = f.input :second_first_name
    = f.input :first_last_name
    = f.input :second_last_name
    = f.input :menor

  .form-actions
    = f.button :submit

app/views/beneficiarios/edit.html.haml
%h1 Editing beneficiario

= render 'form'

= link_to 'Show', @beneficiario
\|
= link_to 'Back', beneficiarios_path

app/views/beneficiarios/index.html.haml
.container
  - breadcrumb :beneficiarios
  .well
    .row
      %h1.col-md-6
        = 'Lista de Beneficiarios'
  .panel.panel-default
    .panel-body
      = form_tag departamentos_path, html: { class: 'navbar-form' }, method: 'get' do
        .input-group
          = text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Buscar'
          .input-group-btn
            = submit_tag 'Buscar', :name => nil, class: 'btn btn-default'

  = will_paginate @beneficiarios, class: 'paginate-bot'

  %table.table.table-striped.table-hover#ctr_row
    %tr
      %th CUI
      %th NOMBRE
      %th SEGUNDO NOMBRE
      %th APELLIDO
      %th SEGUNDO APELLIDO
      %th EDAD
      - if current_user.has_role?(:implementacion) || current_user.has_role?(:admin)
        %th
        %th
        %th

    - @beneficiarios.each do |beneficiario|
      %tr
        %td= beneficiario.cui
        %td= beneficiario.first_name
        %td= beneficiario.second_first_name
        %td= beneficiario.first_last_name
        %td= beneficiario.second_last_name
        %td= beneficiario.age(beneficiario.birth_date)
        - if current_user.has_role?(:implementacion) || current_user.has_role?(:admin)
          %td= link_to 'Ver', beneficiario
          %td= link_to 'Editar', edit_beneficiario_path(beneficiario)
          %td= link_to 'Eliminar', beneficiario, :method => :delete, :data => { :confirm => 'Are you sure?' }

  = will_paginate @beneficiarios, class: 'paginate-bot'

  /= link_to 'New Beneficiario', new_beneficiario_path

app/views/beneficiarios/new.html.haml
%h1 New beneficiario

= render 'form'

= link_to 'Back', beneficiarios_path

app/views/beneficiarios/show.html.haml
.container
  %p#notice= notice

  - breadcrumb :beneficiario, @beneficiario
  .row
    .well
      %h1
        = 'Nombre:'
        %span{style: 'font-weight: 300;'}
          = @beneficiario.first_last_name + ' ' + @beneficiario.second_last_name + ', ' + @beneficiario.first_name + ' ' +  @beneficiario.second_first_name + '.'
      %h2
        = 'CUI: '
        %span{style: 'font-weight: 300;'}
          = @beneficiario.cui
  .row
    .col-md-5
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            = 'Información: '
        .panel-body
          %p
            %b RESIDENCIA:
            = Municipio.find(@beneficiario.municipio).name + ', ' + Departamento.find(@beneficiario.departamento).name + '.'
          %p
            %b FECHA DE NACIMIENTO:
            = @beneficiario.birth_date.day.to_s + ' / ' + @beneficiario.birth_date.month.to_s + ' / ' + @beneficiario.birth_date.year.to_s
          %p
            %b PUEBLO:
            = Pueblo.find(@beneficiario.pueblo).name
          %p
            %b IDIOMA:
            = Idioma.find(@beneficiario.idioma).name
    .col-md-5.col-md-offset-2
      - if @beneficiario.age(@beneficiario.birth_date) < 18
        .panel.panel-default
          .panel-heading
            %h3.panel-title
              = 'PARTIDA DE NACIMIENTO: '
          .panel-body
            %p
              %b No.
              = @beneficiario.no_partida_nacimiento
            %p
              %b Folio.
              = @beneficiario.folio_partida_nacimiento
            %p
              %b Libro.
              = @beneficiario.libro_partida_nacimiento

  /.panel.panel-default
  /  .panel-heading
  /    %h3.panel-title
  /      = 'Beneficiados en: '
  /  .panel-body
  /    %table.table.table-striped.table-hover
  /      %tr
  /        %th CORRELATIVO
  /        %th SOLICITANTE
  /        %th FECHA
  /        %th LUGAR
  /        %th PERFIL
  /    -@beneficiario.solicitud.each do |solicitud|
  /      %tr
  /        %td= solicitud.correlativo

  .row
    .well{style: 'min-height: 70px; margin-top: 2em;'}
      = link_to 'Atras', beneficiarios_path, class: 'btn btn-primary pull-left'
      = link_to 'Editar', edit_beneficiario_path(@beneficiario), class: 'btn btn-primary pull-right'