config/routes.rb
Rails.application.routes.draw do

  resources :soliciteds, except: [:new, :destroy, :index]

  resources :beneficiarios

  resources :solicituds, except: [:edit]
  post '/solicituds/confirmar/:id',    to: 'solicituds#confirmar',      as: 'confirmar_solicitud'
  post '/solicituds/reservar/:id',     to: 'solicituds#reservar',       as: 'reservar_solicitud'
  post '/solicituds/liberar/:id',      to: 'solicituds#liberar',        as: 'liberar_solicitud'
  post '/solicituds/entregar/:id',     to: 'solicituds#entregar',       as: 'entregar_solicitud'
  post '/solicituds/rechazar/:id',     to: 'solicituds#rechazar',       as: 'rechazar_solicitud'
  post '/solicituds/activar/:id',      to: 'solicituds#activar',        as: 'activar_solicitud'
  get '/solicitud/solicitud/:id',      to: 'solicituds#descargar_sol',  as: 'nueva_sol'

  get 'welcome/thankyou'

  get '/reportes/transparencia',     to: 'reportes#transparencia',        as: 'reportes_transparencia'
  get '/reporte/transparencia/:id',  to: 'reportes#transparencia_show',   as: 'reporte_perfil_transparencia'

  resources :implementos

  resources :expedientes

  resources :idiomas

  resources :pueblos

  resources :municipios

  resources :departamentos

  get 'user_dashboard/show'
  get 'user_dashboard/departamentos', as: 'dash_deps'

  resources :pages

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :articles, except: [:new, :destroy]

  devise_for  :users,   controllers: { registrations: 'registrations' }
  resources   :users,   only: [:index, :edit_user]

  get     '/user/:id',              to: 'user#show',          as: :user
  get     '/users/new_user',        to: 'users#new_user',     as: 'admins_new_user'
  post    '/users/create_user',     to: 'users#create_user',  as: 'admins_create_user'
  get     '/users/edit_user/:id',   to: 'users#edit_user',    as: 'admins_edit_user'
  patch   '/users/update_user/:id', to: 'users#update_user',  as: 'admins_update_user'
  delete  '/user/:id',              to: 'users#destroy_user', as: 'admins_destroy_user'

  root 'welcome#index'

end

app/models/solicited.rb
# == Schema Information
#
# Table name: soliciteds
#
#  id            :integer          not null, primary key
#  amount        :integer
#  solicitud_id  :integer
#  implemento_id :integer
#  created_at    :datetime
#  updated_at    :datetime
#  reserved      :integer
#

class Solicited < ActiveRecord::Base
  belongs_to :solicitud
  belongs_to :implemento
  accepts_nested_attributes_for :solicitud
  accepts_nested_attributes_for :implemento
end

app/controllers/soliciteds_controller.rb
class SolicitedsController < ApplicationController
  before_action :set_solicited, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    @soliciteds = Solicited.all
    respond_with(@soliciteds)
  end

  def show
    respond_with(@solicited)
  end

  def new
    @solicited = Solicited.new
    respond_with(@solicited)
  end

  def edit
  end

  def create
    @solicited = Solicited.new(solicited_params)
    @solicited.save
    redirect_to controller: 'solicituds', action: 'show', id: @solicited.solicitud.id
  end

  def update
    @solicited.update(solicited_params)
    redirect_to controller: 'solicituds', action: 'show', id: @solicited.solicitud.id
  end

  def destroy
    @solicited.destroy
    respond_with(@solicited)
  end

  private
    def set_solicited
      @solicited = Solicited.find(params[:id])
    end

    def solicited_params
      params.require(:solicited).permit(:amount, :solicitud_id, :implemento_id,
                                        implemento_attributes: [:id, :name, :piezas, :description,
                                                                :available, :reserved, :solicited],
                                        implementos_attribute: [:id, :name, :piezas, :description,
                                                                :available, :reserved, :solicited],
                                        solicitud_attributes: []
                                       )
    end
end

app/helpers/soliciteds_helper.rb
module SolicitedsHelper
end

app/views/soliciteds/_form.html.haml
= simple_form_for @solicited, html: { class: 'form-devise' } do |f|
  = f.error_notification

  .form-inputs
    = f.text_field :amount, class: 'form-control sole', label: 'Cantidad'
    /= f.input :solicitud_id, class: 'form-control sole'
    /= f.input :implemento_id, class: 'form-control sole'

  .form-actions
    = f.submit 'Cambiar', class: 'btn btn-lg btn-primary btn-block'

app/views/soliciteds/edit.html.haml
.container
  .well
    .row
      %h1.col-md-6
        = 'Editando Cantidad Solicitada'
      .col-md-6
        = link_to 'Regresar', solicitud_path(@solicited.solicitud.id), class: 'btn btn-default pull-right title-btn'
    %br

= render 'form'

/
  = link_to 'Show', @solicited
  \|
  = link_to 'Back', soliciteds_path

app/views/soliciteds/index.html.haml
%h1 Listing soliciteds

%table
  %tr
    %th Amount
    %th Solicitud
    %th Implemento
    %th
    %th
    %th

  - @soliciteds.each do |solicited|
    %tr
      %td= solicited.amount
      %td= solicited.solicitud_id
      %td= solicited.implemento_id
      %td= link_to 'Show', solicited
      %td= link_to 'Edit', edit_solicited_path(solicited)
      %td= link_to 'Destroy', solicited, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Solicited', new_solicited_path

app/views/soliciteds/new.html.haml
%h1 New solicited

= render 'form'

= link_to 'Back', soliciteds_path

app/views/soliciteds/show.html.haml
%p#notice= notice

%p
  %b Amount:
  = @solicited.amount
%p
  %b Solicitud:
  = @solicited.solicitud_id
%p
  %b Implemento:
  = @solicited.implemento_id

= link_to 'Edit', edit_solicited_path(@solicited)
\|
= link_to 'Back', soliciteds_path