config/routes.rb
Rails.application.routes.draw do

  resources :soliciteds, except: [:new, :destroy, :index]

  resources :beneficiarios

  resources :solicituds, except: [:edit]
  post '/solicituds/confirmar/:id',    to: 'solicituds#confirmar',      as: 'confirmar_solicitud'
  post '/solicituds/reservar/:id',     to: 'solicituds#reservar',       as: 'reservar_solicitud'
  post '/solicituds/liberar/:id',      to: 'solicituds#liberar',        as: 'liberar_solicitud'
  post '/solicituds/entregar/:id',     to: 'solicituds#entregar',       as: 'entregar_solicitud'
  post '/solicituds/rechazar/:id',     to: 'solicituds#rechazar',       as: 'rechazar_solicitud'
  post '/solicituds/activar/:id',      to: 'solicituds#activar',        as: 'activar_solicitud'
  get '/solicitud/solicitud/:id',      to: 'solicituds#descargar_sol',  as: 'nueva_sol'

  get 'welcome/thankyou'

  get '/reportes/transparencia',     to: 'reportes#transparencia',        as: 'reportes_transparencia'
  get '/reporte/transparencia/:id',  to: 'reportes#transparencia_show',   as: 'reporte_perfil_transparencia'

  resources :implementos

  resources :expedientes

  resources :idiomas

  resources :pueblos

  resources :municipios

  resources :departamentos

  get 'user_dashboard/show'
  get 'user_dashboard/departamentos', as: 'dash_deps'

  resources :pages

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :articles, except: [:new, :destroy]

  devise_for  :users,   controllers: { registrations: 'registrations' }
  resources   :users,   only: [:index, :edit_user]

  get     '/user/:id',              to: 'user#show',          as: :user
  get     '/users/new_user',        to: 'users#new_user',     as: 'admins_new_user'
  post    '/users/create_user',     to: 'users#create_user',  as: 'admins_create_user'
  get     '/users/edit_user/:id',   to: 'users#edit_user',    as: 'admins_edit_user'
  patch   '/users/update_user/:id', to: 'users#update_user',  as: 'admins_update_user'
  delete  '/user/:id',              to: 'users#destroy_user', as: 'admins_destroy_user'

  root 'welcome#index'

end

app/models/departamento.rb
# == Schema Information
#
# Table name: departamentos
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Departamento < ActiveRecord::Base
  has_many :municipios
  has_many :solicituds
  validates :name, presence: true

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    @departamentos = Departamento.search(params[:search]).paginate(:page => params[:page], :per_page => 10)
    respond_with(@departamentos)
  end

  def show
    @departamento = Departamento.find(params[:id])
    @municipios = @departamento.municipios.paginate(:page => params[:page], :per_page => 10)
    respond_with(@departamento)
  end

  def new
    @departamento = Departamento.new
    respond_with(@departamento)
  end

  def edit
  end

  def create
    @departamento = Departamento.new(departamento_params)
    @departamento.save
    respond_with(@departamento)
  end

  def update
    @departamento.update(departamento_params)
    respond_with(@departamento)
  end

  def destroy
    @departamento.destroy
    respond_with(@departamento)
  end

  private
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    def departamento_params
      params.require(:departamento).permit(:name, :solicitud_id)
    end
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/departamentos/_form.html.haml
= simple_form_for @departamento, html: { class: 'form-devise' } do |f|
  = f.error_notification

  .form-inputs
    = f.label 'Nombre'
    = f.text_field :name, class: 'form-control sole'
  .form-actions
    = f.error :base
    = f.submit 'Guardar', :class => 'btn btn-lg btn-primary btn-block'

app/views/departamentos/edit.html.haml
.container
  .well
    .row
      %h1.col-md-6
        = 'Editando Departamento'
      .col-md-6
        = link_to 'Regresar', departamentos_path, class: 'btn btn-default pull-right title-btn'
    %br

  = render 'form'

app/views/departamentos/index.html.haml
.container
  - breadcrumb :departamentos
  .well
    .row
      %h1.col-md-6
        = 'Lista de Departamentos'
      .col-md-6
        = link_to 'Agregar Departamento', new_departamento_path, class: 'btn btn-default pull-right title-btn'
  %br

  .panel.panel-default
    .panel-body
      = form_tag departamentos_path, html: { class: 'navbar-form' }, method: 'get' do
        .input-group
          = text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Buscar'
          .input-group-btn
            = submit_tag 'Buscar', :name => nil, class: 'btn btn-default'


  %table.table.table-striped.table-hover

    - @departamentos.each do |departamento|
      %tr
        %td= departamento.name
        %td= link_to 'Municipios', departamento
        %td= link_to 'Editar', edit_departamento_path(departamento)
        %td= link_to 'Eliminar', departamento, :method => :delete, :data => { :confirm => 'Confirmar.' }

  = will_paginate @departamentos, class: 'paginate-bot'

app/views/departamentos/new.html.haml
.container
  .well
    .row
      %h1.col-md-6
        = 'Nuevo Departamento'
      .col-md-6
        = link_to 'Regresar', departamentos_path, class: 'btn btn-default pull-right title-btn'

  = render 'form'

app/views/departamentos/show.html.haml
.container
  %p#notice= notice
  - breadcrumb :departamento, @departamento

  .well
    .row
      %h1.col-md-6
        = 'Municipios de '
        = @departamento.name
      .col-md-6
        = link_to 'Editar', edit_departamento_path(@departamento), class: 'btn btn-default pull-right title-btn', style: 'margin-left: 1em;'
        = link_to 'Regresar', departamentos_path, class: 'btn btn-default pull-right title-btn'

  %table.table.table-striped.table-hover

    - @municipios.each do |muni|
      %tr
        %td= muni.name
        %td= link_to 'Editar', edit_municipio_path(muni)
        %td= link_to 'Eliminar', muni, :method => :delete, :data => { :confirm => 'Confirmar.' }

  = will_paginate @municipios, class: 'paginate-bot'