config/routes.rb
Rails.application.routes.draw do

  resources :soliciteds, except: [:new, :destroy, :index]

  resources :beneficiarios

  resources :solicituds, except: [:edit]
  post '/solicituds/confirmar/:id',    to: 'solicituds#confirmar',      as: 'confirmar_solicitud'
  post '/solicituds/reservar/:id',     to: 'solicituds#reservar',       as: 'reservar_solicitud'
  post '/solicituds/liberar/:id',      to: 'solicituds#liberar',        as: 'liberar_solicitud'
  post '/solicituds/entregar/:id',     to: 'solicituds#entregar',       as: 'entregar_solicitud'
  post '/solicituds/rechazar/:id',     to: 'solicituds#rechazar',       as: 'rechazar_solicitud'
  post '/solicituds/activar/:id',      to: 'solicituds#activar',        as: 'activar_solicitud'
  get '/solicitud/solicitud/:id',      to: 'solicituds#descargar_sol',  as: 'nueva_sol'

  get 'welcome/thankyou'

  get '/reportes/transparencia',     to: 'reportes#transparencia',        as: 'reportes_transparencia'
  get '/reporte/transparencia/:id',  to: 'reportes#transparencia_show',   as: 'reporte_perfil_transparencia'

  resources :implementos

  resources :expedientes

  resources :idiomas

  resources :pueblos

  resources :municipios

  resources :departamentos

  get 'user_dashboard/show'
  get 'user_dashboard/departamentos', as: 'dash_deps'

  resources :pages

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :articles, except: [:new, :destroy]

  devise_for  :users,   controllers: { registrations: 'registrations' }
  resources   :users,   only: [:index, :edit_user]

  get     '/user/:id',              to: 'user#show',          as: :user
  get     '/users/new_user',        to: 'users#new_user',     as: 'admins_new_user'
  post    '/users/create_user',     to: 'users#create_user',  as: 'admins_create_user'
  get     '/users/edit_user/:id',   to: 'users#edit_user',    as: 'admins_edit_user'
  patch   '/users/update_user/:id', to: 'users#update_user',  as: 'admins_update_user'
  delete  '/user/:id',              to: 'users#destroy_user', as: 'admins_destroy_user'

  root 'welcome#index'

end

app/controllers/user_dashboard_controller.rb
class UserDashboardController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @solicitudes = Solicitud.order(created_at: :desc)
    # Dataset Departamento
    @departamentos = Departamento.order(:id)
    labels_deps = @departamentos.map { |d| d.name }
    dt_values = []
    @departamentos.each do |ds|
      dt_values << ds.solicituds.count
    end
    @deps_solis = {
        labels: labels_deps,
        datasets: [
            {
                label: 'Solicitudes',
                fillColor: 'rgba(151,187,205,0.5)',
                strokeColor: 'rgba(151,187,205,1)',
                pointColor: 'rgba(151,187,205,1)',
                pointStrokeColor: '#fff',
                data: dt_values
            }
        ]
    }
    # Implementos
    @idelivered = 0
    @ireserved = 0
    @iavailable = 0
    @implementos = Implemento.all
    @implementos.each do |i|
      @idelivered += i.total_delivered
      @ireserved += i.total_reserved
      @iavailable += i.available
    end
    @dataDisp = [
        {
            value: @iavailable,
            color: "#46BFBD",
            highlight: "#5AD3D1",
            label: 'Disponibles'
        },
        {
            value: @ireserved,
            color: "#FDB45C",
            highlight: "#FFC870",
            label: 'Reservados'
        },
        {
            value: @idelivered,
            color: "#949FB1",
            highlight: "#A8B3C5",
            label: 'No Disponibles'
        }
    ]

    # Dataset Solicitudes Estado
    @dataState = [
        {
            value: @solicitudes.where('state=?', 'rechazado').count,
            color:"#F7464A",
            highlight: "#FF5A5E",
            label: 'Rechazado'
        },
        {
            value: @solicitudes.where('state=?', 'reservado').count,
            color: "#46BFBD",
            highlight: "#5AD3D1",
            label: 'Reservado'
        },
        {
            value: @solicitudes.where('state=?', 'pendiente').count,
            color: "#FDB45C",
            highlight: "#FFC870",
            label: 'Pendiente'
        },
        {
            value: @solicitudes.where('state=?', 'confirmado').count,
            color: "#949FB1",
            highlight: "#A8B3C5",
            label: 'Confirmado'
        },
        {
            value: @solicitudes.where('state=?', 'entregado').count,
            color: "#4D5360",
            highlight: "#616774",
            label: 'Entregado'
        }

    ]

  end

  def departamentos
    @departamentos = Departamento.order(:id)
  end

end

app/helpers/user_dashboard_helper.rb
module UserDashboardHelper
end

app/views/user_dashboard/_admin_dash.html.haml
.row
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-map-marker.dash-icon.fa-4x
    %h3
      = link_to 'Departamentos', departamentos_path
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-map-marker.dash-icon.fa-4x
    %h3
      = link_to 'Municipios', municipios_path
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-users.dash-icon.fa-4x
    %h3
      = link_to 'Usuarios', users_path
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-language.dash-icon.fa-4x
    %h3
      = link_to 'Idiomas', idiomas_path
.row{style: 'margin-top: 5em;'}
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-globe.dash-icon.fa-4x
    %h3
      = link_to 'Pueblos', pueblos_path
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-futbol-o.dash-icon.fa-4x
    %h3
      = link_to 'Implementos', implementos_path
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-file-text.dash-icon.fa-4x
    %h3
      = link_to 'Contenido', articles_path
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-suitcase.dash-icon.fa-4x
    %h3
      = link_to 'Solicitudes', solicituds_path
.row{style: 'margin-top: 5em;'}
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-child.dash-icon.fa-4x
    %h3
      = link_to 'Beneficiarios', beneficiarios_path

app/views/user_dashboard/_graph_ventanilla.html.haml
.row
  .col-md-8.col-md-offset-2
    .panel.panel-info
      .panel-heading
        %h3.panel-title
          = 'Departamentos'
      .panel-body
        .col-md-11
          = content_tag 'div', id: 'datos_deps_vent', data: { departamentos: @deps_solis } do
            %p.graph_desc
              = 'Solicitudes por Departamento.'
            %p
              = 'Total de solicitudes: ' + @solicitudes.count.to_s
          %canvas#cvsdepsvent{height: '450', width: '600'}
            = 'Su navegador no es compatible, por favor descargue una nueva versión.'

app/views/user_dashboard/_graphs.html.haml
.row
  .col-md-4
    .panel.panel-info
      .panel-heading
        %h3.panel-title
          = 'Solicitudes por Estado'
      .panel-body
        .col-md-11
          = content_tag 'div', id: 'datos_sols', data: { solis: @dataState } do
            %p.hidden
              = 'Solicitudes por estados.'
          %canvas#cvssolicitudes{height: '450', width: '600'}
            = 'Su navegador no es compatible, por favor descargue una nueva versión.'
    .panel.panel-info
      .panel-heading
        %h3.panel-title
          = 'Implementos Disponibles'
      .panel-body
        .col-md-11
          = content_tag 'div', id: 'datos_imps', data: { disponibilidad: @dataDisp } do
            %p.hidden
              = 'Implementos Disponibles.'
          %canvas#cvsimps{height: '450', width: '600'}
            = 'Su navegador no es compatible, por favor descargue una nueva versión.'
  .col-md-8
    .panel.panel-info
      .panel-heading
        %h3.panel-title
          = 'Departamentos'
      .panel-body
        .col-md-11
          = content_tag 'div', id: 'datos_deps', data: { departamentos: @deps_solis } do
            %p.graph_desc
              = 'Solicitudes por Departamento.'
            %p
              = 'Total de solicitudes: ' + @solicitudes.count.to_s
          %canvas#cvsdeps{height: '450', width: '600'}
            = 'Su navegador no es compatible, por favor descargue una nueva versión.'

app/views/user_dashboard/_implementacion_dash.html.haml
.row{style: 'margin-top: 2%; margin-bottom: 5%;'}
  %h2{align: 'center'} Módulos
  %br
  %br
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-child.dash-icon.fa-4x
    %h3
      = link_to 'Beneficiarios', beneficiarios_path
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-suitcase.dash-icon.fa-4x
    %h3
      = link_to 'Solicitudes', solicituds_path
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-users.dash-icon.fa-4x
    %h3
      = link_to 'Usuarios', users_path
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-language.dash-icon.fa-4x
    %h3
      = link_to 'Idiomas', idiomas_path
.row{style: 'margin-top: 5em;'}
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-globe.dash-icon.fa-4x
    %h3
      = link_to 'Pueblos', pueblos_path
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-futbol-o.dash-icon.fa-4x
    %h3
      = link_to 'Implementos', implementos_path
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-file-text.dash-icon.fa-4x
    %h3
      = link_to 'Contenido', articles_path

app/views/user_dashboard/_supervisor_dash.html.haml
.row{style: 'margin-top: 2%; margin-bottom: 5%;'}
  %h2{align: 'center'} Módulos
  %br
  %br
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-futbol-o.dash-icon.fa-4x
    %h3
      = link_to 'Implementos', implementos_path

  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-suitcase.dash-icon.fa-4x
    %h3
      = link_to 'Solicitudes', solicituds_path

  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-child.dash-icon.fa-4x
    %h3
      = link_to 'Beneficiarios', beneficiarios_path

  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-suitcase.dash-icon.fa-4x
    %h3
      = link_to 'Departamentos', dash_deps_path

app/views/user_dashboard/_ventanilla_dash.html.haml
.row{style: 'margin-top: 2%; margin-bottom: 5%;'}
  %h2{align: 'center'} Módulos
  %br
  %br
  .col-sm-3.col-md-3.col-md-offset-3.dash-cont
    %i.fa.fa-suitcase.dash-icon.fa-4x
    %h3
      = link_to 'Solicitudes', solicituds_path
  .col-sm-3.col-md-3.dash-cont
    %i.fa.fa-child.dash-icon.fa-4x
    %h3
      = link_to 'Beneficiarios', beneficiarios_path

app/views/user_dashboard/departamentos.html.haml
.container
  - breadcrumb :dash_dep, current_user
  .well
    .row
      %h2{align: 'center'}
        = 'Solicitudes por Departamento y Municipio'
  .rep_departamentos
    #accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
      - ctr = 0
      - ctrm = 0
      -@departamentos.each do |depart|
        - if depart.solicituds.where('state = ?', 'entregado').count > 0
          .panel.panel-default
            %a{"aria-controls" => "collapse#{ctr}", "aria-expanded" => "true", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapse#{ctr}", class: 'panel-title'}
              #headingOne.panel-heading{:role => "tab"}
                %h4
                  = depart.name
                %span.badge{style: 'float:right; margin-top: -25px; background-color: #428bca;'}
                  = depart.solicituds.where('state = ?', 'entregado').count
            %div{"aria-labelledby" => "headingOne", :role => "tabpanel", class: "panel-collapse collapse", id: "collapse#{ctr}"}
              .panel-body
                .rep_munis
                  #accordion-munis.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
                    - depart.municipios.each do |m|
                      - if m.solicituds.where('state = ?', 'entregado').count > 0
                        .panel.panel-default
                          %a{"aria-controls" => "collapsem#{ctrm}", "aria-expanded" => "true", "data-parent" => "#accordion-munis", "data-toggle" => "collapse", :href => "#collapsem#{ctrm}"}
                            %div{:role => "tab", class: 'panel-heading', id: "heading#{ctrm}", style: 'background-color: #f3f3f3; '}
                              %h4.panel-title
                                = m.name
                                %span.badge{style: 'float:right; background-color: #FF915C;'}
                                  = m.solicituds.where('state = ?', 'entregado').count
                          %div{"aria-labelledby" => "heading#{ctrm}", :role => "tabpanel", class: "panel-collapse collapse", id: "collapsem#{ctrm}"}
                            .panel-body
                              %table.table.table-hover.table-striped#ctr_row
                                %tr
                                  %th UBICACIÓN
                                  %th REPRESENTANTE
                                  %th FECHA DE ENTREGA
                                  %th PERFIL

                                - m.solicituds.each do |solicitud|
                                  - if solicitud.entregado?
                                    %tr
                                      %td= ubicacion(solicitud)
                                      %td= solicitud.representante
                                      %td= human_date(solicitud.fecha_entrega)
                                      %td= link_to 'Ver', reporte_perfil_transparencia_path(solicitud)

                              %br

                        - ctrm += 1
        - ctr += 1

app/views/user_dashboard/show.html.haml
.row#dash_row
  .dash_sidebar.col-md-2
    = image_tag @user.avatar_url(:thumb), width: '200', class: 'avatar img-responsive'
    %h1.name
      = full_name(current_user)
    %h4.email
      = current_user.email

  .col-md-8.col-md-offset-1
    %br
    %br
    - if current_user.admin?
      .well
        %h1
          = 'Administrador'
      %br
      %br
      = render 'admin_dash'
    - elsif current_user.has_role? :supervisor
      = render 'graphs'
      %br
      %br
      .well
        = render 'supervisor_dash'
    - elsif current_user.has_role? :implementacion
      = render 'graphs'
      %br
      %br
      .well
        = render 'implementacion_dash'
        %br
    - elsif current_user.has_role? :ventanilla
      = render 'graph_ventanilla'
      %br
      %br
      .well
        = render 'ventanilla_dash'
    - else
      .well
        %h1
          = 'Solicite permisos adicionales al administrador.'